INSERT INTO locations (id, city, address) VALUES (wydawaæ siê, Kraœnik, aleja Wyszyñskiego 808);
INSERT INTO locations (id, city, address) VALUES (rysunek, Suwa³ki, aleja Przemys³owa 054);
INSERT INTO locations (id, city, address) VALUES (gruby, D¹browa Górnicza, pl. Strzelecka 483);
INSERT INTO locations (id, city, address) VALUES (dobro, Swarzêdz, pl. Strzelecka 409);
INSERT INTO locations (id, city, address) VALUES (samiec, Grudzi¹dz, al. Krzywa 21);
INSERT INTO locations (id, city, address) VALUES (zero, Zabrze, ulica Poniatowskiego 18);
INSERT INTO locations (id, city, address) VALUES (biskup, Zduñska Wola, ul. M³ynarska 33/86);
INSERT INTO locations (id, city, address) VALUES (osi¹gn¹æ, P³oñsk, ulica Spokojna 985);
INSERT INTO locations (id, city, address) VALUES (przesz³oœæ, Chojnice, ulica ¯urawia 64/19);
INSERT INTO locations (id, city, address) VALUES (wódka, Siedlce, plac Dojazdowa 60);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (z³oty, Ada Kosiak, ryszard52@example.com, 693 238 584, 2025-02-25 08:58:01);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (pañstwowy, pani Janina Tomys, szybiaksara@example.com, +48 798 047 395, 2025-01-14 09:21:40);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (pi³ka no¿na, Ró¿a Bednarowicz, oskar49@example.com, 881 726 384, 2025-01-13 15:57:48);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (udaæ siê, Gabriel Dmoch, patryknytko@example.org, +48 32 094 03 45, 2025-02-04 06:42:28);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (sierpieñ, Natasza Sypu³a, maciej86@example.net, 786 375 623, 2025-04-08 03:08:50);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (by, Marcin Januszewicz, maciej38@example.net, 32 268 62 72, 2025-01-23 21:21:49);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (ca³kowicie, Lidia Glego³a, martynnatasza@example.net, +48 22 420 31 40, 2025-01-13 13:35:39);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (ruch, Anastazja Matura, leszczroza@example.com, +48 782 777 694, 2025-01-15 08:50:51);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (powierzchnia, pan Konrad Cyrek, igor60@example.net, 600 074 973, 2025-03-30 11:27:59);
INSERT INTO clients (id, full_name, email, phone, created_at) VALUES (graniczyæ, Nela Ankiewicz, osadaliwia@example.org, +48 504 678 404, 2025-01-20 09:26:04);
INSERT INTO bike_types (id, name) VALUES (wejœæ, s¹dowy);
INSERT INTO bike_types (id, name) VALUES (wyrok, opisaæ);
INSERT INTO bike_types (id, name) VALUES (filozofia, oraz);
INSERT INTO bike_types (id, name) VALUES (zapach, dotyczyæ);
INSERT INTO bike_types (id, name) VALUES (dok³adny, adres);
INSERT INTO bike_types (id, name) VALUES (pe³en, lot);
INSERT INTO bike_types (id, name) VALUES (fa³szywy, zanim);
INSERT INTO bike_types (id, name) VALUES (z³apaæ, przesz³oœæ);
INSERT INTO bike_types (id, name) VALUES (wœród, pani);
INSERT INTO bike_types (id, name) VALUES (nie ma, spotkaæ);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (grecki, majusku³a, kolumna, przestrzeñ, nigdy, koñ);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (dok³adnie, doros³y, umowa, zainteresowanie, zanim, ukraiñski);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (szef, sztuczny, postêpowaæ, pies, ha³as, atak);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (dziwny, gleba, otworzyæ, g³upota, bogini, ptak);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (grupa, kwiecieñ, czynnik, opisaæ, 900, wydaæ);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (mebel, miara, bliski, Szwecja, gdzieœ, powstanie);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (nag³y, radiowy, ig³a, no, wejœcie, kwiat);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (³agodny, ³ó¿ko, wskazywaæ, podaæ, rada, pozostaæ);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (postawiæ, Japonia, warstwa, wrogoœæ, ale, idea);
INSERT INTO discounts (id, name, description, percentage, valid_from, valid_to) VALUES (Wêgry, transport, projekt, sukienka, k³opot, ³agodny);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (bieda, tylko, g³ównie, ci, gospodarka, -99309025358629.1);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (adres, fakt, biedny, wydaæ, artyku³, -71356844.256566);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (wrogi, wycieczka, gard³o, grunt, w³o¿yæ, -171.837780764591);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (stan, obiekt, ³ódŸ, grób, kartka, -7246.56689380812);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (stolica, Indie, tak, z krwi i koœci, zw³aszcza, 16394.5837304);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (koszt, bóg, lub, zapach, czêœciowo, -929915136.336696);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (przyczyna, inny, zero, ja, nasz, 4037.41525640037);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (sierpieñ, uczucie, w ci¹gu, sylaba, grób, -13.8518298412125);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (60, ponownie, projekt, prasa, urzêdnik, -5075379.12492247);
INSERT INTO bikes (id, model, type_id, location_id, status, daily_price) VALUES (poeta, miara, otaczaæ, produkowaæ, mi³oœæ, 46.427858873429);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (mocno, dok³adny, kolejny, przedsiêbiorstwo, dziwny, -4112515965905.77, lêk, idea, róg, wystawa);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (p³yn¹æ, ró¿owy, wszystko, piêtro, chiñski, 188119704.938, skóra, tajemnica, przejaw, przyjemny);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (³atwo, móc, z¹b, taniec, te, -1586053630215.4, szósty, udzia³, W³ochy, aktor);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (dziadek, (…), ska³a, staro¿ytny, zamykaæ, -6996334319.56686, b¹dŸ, Ÿle, przyprawa, stawiaæ);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (pszczo³a, wspólnota, szczególnie, œniadanie, Grecja, 326.451742427028, but, dzisiaj, student, narz¹d);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (obowi¹zek, p³yn, gotowaæ, paj¹k, kolejny, 8493.3293212454, pochodziæ, ca³kowity, ty³, on);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (poza, stosowaæ, skala, elektryczny, stosowaæ, 25.4172349999023, rozmawiaæ, pañstwo, sobie, wartoœæ);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (8, strata, s³u¿yæ, straciæ, wed³ug, 2059498323281.18, plama, pokryæ, zbiornik, lek);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (Stany Zjednoczone, srebrny, ch³opak, dolny, król, 2350235356636.46, nadmierny, gniazdo, nauczycielka, 6);
INSERT INTO rentals (id, client_id, bike_id, rental_start, rental_end, total_price, location_pickup_id, location_dropoff_id, discount_id, status) VALUES (widok, autor, czyniæ, oddech, jeszcze, 52447215412.7578, minister, tam, 1, poeta);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (rz¹d, zazwyczaj, ¿ywnoœæ, 2025-02-11 02:45:55);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (zwyciêstwo, pewien, dziadek, 2025-03-19 19:28:42);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (syn, sukces, mieæ na imiê, 2025-02-07 16:49:33);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (po³¹czenie, cienki, nie ma, 2025-03-12 16:08:45);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (wodny, g³upota, po³udnie, 2025-01-03 07:40:39);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (herb, aby, instytucja, 2025-01-08 07:05:20);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (mierzyæ, strefa, dziewiêæ, 2025-03-26 15:24:17);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (w wyniku, nastêpny, sprawa, 2025-03-30 23:36:28);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (broñ, czyniæ, wakacje, 2025-01-15 23:08:03);
INSERT INTO maintenance_logs (id, bike_id, description, maintenance_date) VALUES (powieœæ, pozostawaæ, œwie¿y, 2025-02-17 08:50:29);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (tworzyæ, wiêkszy, -688510.789371542);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (dziewczynka, handlowy, -9985947930.59979);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (dobrze, blady, -408985435370.268);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (czasownik, obywatel, -7409.5724004786);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (czy, jednoczeœnie, 56127937682938.1);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (powstaæ, przyjœæ, 99.5364228369265);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (ludzie, wed³ug, -10430117134.9819);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (wierny, rzadko, 48643283088665.5);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (telewizja, trzymaæ, 230752.796233151);
INSERT INTO bike_accessories (id, name, daily_price) VALUES (uznawaæ, styl, -948.892341454692);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (charakter, lista, mo¿liwoœæ);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (zwyciêstwo, w³asnoœæ, dzielnica);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (sytuacja, oddzia³, has³o);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (œroda, dru¿yna, wysokoœæ);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (60, maszyna, ludnoœæ);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (ogon, pewien, mo¿liwy);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (przez, przyjemny, bycie);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (gêœ, przez, prezydent);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (maj¹tek, powa¿ny, warzywo);
INSERT INTO rental_accessories (rental_id, accessory_id, quantity) VALUES (bliski, dobry, taniec);
